[project]
name = "frame-server"
version = "0.1.0"
description = "Web server for uploading photos to the digital picture frame"
readme = "README.md"
license = "AGPL-3.0"
authors = [{name = "Daniel Mikusa"}]
requires-python = ">=3.10"
dependencies = [
    "photo-manager",
]

[project.scripts]
frame-server = "frame_server.server:main"
frame-client = "frame_server.client:main"

[tool.uv.sources]
photo-manager = { workspace = true }

[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "coverage>=7.11.0",
    "pyright>=1.1.406",
    "pytest>=8.4.2",
    "ruff>=0.14.1",
]

[tool.pyright]
include = ["src/frame_server"]
exclude = ["**/__pycache__"]
pythonVersion = "3.11"
pythonPlatform = "Linux"

[tool.pytest.ini_options]
testpaths = ["src/frame_server"]
addopts = [
    "--strict-markers",
    "--strict-config",
]